-- Automation notifications — generated by cron jobs, consumed by the app
CREATE TABLE IF NOT EXISTS notifications (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type        text NOT NULL,
  title       text NOT NULL,
  body        text,
  data        jsonb NOT NULL DEFAULT '{}',
  read        boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  day         date NOT NULL DEFAULT CURRENT_DATE  -- for deduplication (one per type per day)
);

CREATE INDEX IF NOT EXISTS notifications_created_at_idx ON notifications (created_at DESC);

-- One notification per type per calendar day
CREATE UNIQUE INDEX IF NOT EXISTS notifications_type_day_idx ON notifications (type, day);
